plots:
- nodes/DCM_H2SO4/ASEMD/metrics_dict.csv: {}
- nodes/H2O_AcAc/ASEMD/metrics_dict.csv: {}
- nodes/ASA/ASEMD/metrics_dict.csv: {}
stages:
  ASA_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name ASA_ASEGeoOpt
    deps:
    - nodes/ASA/Packmol/atoms.h5
    - nodes/ASA/Packmol/node-meta.json
    - nodes/ASA/Packmol/packmol
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/ASA/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/ASA/ASEGeoOpt/model_outs
    - nodes/ASA/ASEGeoOpt/trajectory.h5
    params:
    - ASA_ASEGeoOpt
  ASA_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name ASA_ASEMD
    deps:
    - nodes/ASA/ASEGeoOpt/model_outs
    - nodes/ASA/ASEGeoOpt/node-meta.json
    - nodes/ASA/ASEGeoOpt/trajectory.h5
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/ASA/ASEMD/node-meta.json:
        cache: false
    - nodes/ASA/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/ASA/ASEMD/metrics_dict.csv
    - nodes/ASA/ASEMD/model
    - nodes/ASA/ASEMD/trajectory.h5
    params:
    - ASA_ASEMD
    - ASA_ASEMD+thermostat
  ASA_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name ASA_Packmol
    deps:
    - nodes/ASA/SmilesToAtoms/atoms.h5
    - nodes/ASA/SmilesToAtoms/molecule.png
    - nodes/ASA/SmilesToAtoms/node-meta.json
    - nodes/ASA/SmilesToAtoms_1/atoms.h5
    - nodes/ASA/SmilesToAtoms_1/molecule.png
    - nodes/ASA/SmilesToAtoms_1/node-meta.json
    - nodes/ASA/SmilesToAtoms_2/atoms.h5
    - nodes/ASA/SmilesToAtoms_2/molecule.png
    - nodes/ASA/SmilesToAtoms_2/node-meta.json
    metrics:
    - nodes/ASA/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/ASA/Packmol/atoms.h5
    - nodes/ASA/Packmol/packmol
    params:
    - ASA_Packmol
  ASA_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name ASA_SmilesToAtoms
    metrics:
    - nodes/ASA/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/ASA/SmilesToAtoms/atoms.h5
    - nodes/ASA/SmilesToAtoms/molecule.png
    params:
    - ASA_SmilesToAtoms
  ASA_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name ASA_SmilesToAtoms_1
    metrics:
    - nodes/ASA/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/ASA/SmilesToAtoms_1/atoms.h5
    - nodes/ASA/SmilesToAtoms_1/molecule.png
    params:
    - ASA_SmilesToAtoms_1
  ASA_SmilesToAtoms_2:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name ASA_SmilesToAtoms_2
    metrics:
    - nodes/ASA/SmilesToAtoms_2/node-meta.json:
        cache: false
    outs:
    - nodes/ASA/SmilesToAtoms_2/atoms.h5
    - nodes/ASA/SmilesToAtoms_2/molecule.png
    params:
    - ASA_SmilesToAtoms_2
  DCM_H2SO4_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name DCM_H2SO4_ASEGeoOpt
    deps:
    - nodes/DCM_H2SO4/Packmol/atoms.h5
    - nodes/DCM_H2SO4/Packmol/node-meta.json
    - nodes/DCM_H2SO4/Packmol/packmol
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/DCM_H2SO4/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/DCM_H2SO4/ASEGeoOpt/model_outs
    - nodes/DCM_H2SO4/ASEGeoOpt/trajectory.h5
    params:
    - DCM_H2SO4_ASEGeoOpt
  DCM_H2SO4_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name DCM_H2SO4_ASEMD
    deps:
    - nodes/DCM_H2SO4/ASEGeoOpt/model_outs
    - nodes/DCM_H2SO4/ASEGeoOpt/node-meta.json
    - nodes/DCM_H2SO4/ASEGeoOpt/trajectory.h5
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/DCM_H2SO4/ASEMD/node-meta.json:
        cache: false
    - nodes/DCM_H2SO4/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/DCM_H2SO4/ASEMD/metrics_dict.csv
    - nodes/DCM_H2SO4/ASEMD/model
    - nodes/DCM_H2SO4/ASEMD/trajectory.h5
    params:
    - DCM_H2SO4_ASEMD
    - DCM_H2SO4_ASEMD+thermostat
  DCM_H2SO4_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name DCM_H2SO4_Packmol
    deps:
    - nodes/DCM_H2SO4/SmilesToAtoms/atoms.h5
    - nodes/DCM_H2SO4/SmilesToAtoms/molecule.png
    - nodes/DCM_H2SO4/SmilesToAtoms/node-meta.json
    - nodes/DCM_H2SO4/SmilesToAtoms_1/atoms.h5
    - nodes/DCM_H2SO4/SmilesToAtoms_1/molecule.png
    - nodes/DCM_H2SO4/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/DCM_H2SO4/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/DCM_H2SO4/Packmol/atoms.h5
    - nodes/DCM_H2SO4/Packmol/packmol
    params:
    - DCM_H2SO4_Packmol
  DCM_H2SO4_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name DCM_H2SO4_SmilesToAtoms
    metrics:
    - nodes/DCM_H2SO4/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/DCM_H2SO4/SmilesToAtoms/atoms.h5
    - nodes/DCM_H2SO4/SmilesToAtoms/molecule.png
    params:
    - DCM_H2SO4_SmilesToAtoms
  DCM_H2SO4_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name DCM_H2SO4_SmilesToAtoms_1
    metrics:
    - nodes/DCM_H2SO4/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/DCM_H2SO4/SmilesToAtoms_1/atoms.h5
    - nodes/DCM_H2SO4/SmilesToAtoms_1/molecule.png
    params:
    - DCM_H2SO4_SmilesToAtoms_1
  H2O_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name H2O_ASEGeoOpt
    deps:
    - nodes/H2O/Packmol/atoms.h5
    - nodes/H2O/Packmol/node-meta.json
    - nodes/H2O/Packmol/packmol
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/H2O/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/H2O/ASEGeoOpt/model_outs
    - nodes/H2O/ASEGeoOpt/trajectory.h5
    params:
    - H2O_ASEGeoOpt
  H2O_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name H2O_ASEMD
    deps:
    - nodes/H2O/ASEGeoOpt/model_outs
    - nodes/H2O/ASEGeoOpt/node-meta.json
    - nodes/H2O/ASEGeoOpt/trajectory.h5
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/H2O/ASEMD/node-meta.json:
        cache: false
    - nodes/H2O/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/H2O/ASEMD/metrics_dict.csv
    - nodes/H2O/ASEMD/model
    - nodes/H2O/ASEMD/trajectory.h5
    params:
    - H2O_ASEMD
    - H2O_ASEMD+thermostat
  H2O_AcAc_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name H2O_AcAc_ASEGeoOpt
    deps:
    - nodes/H2O_AcAc/Packmol/atoms.h5
    - nodes/H2O_AcAc/Packmol/node-meta.json
    - nodes/H2O_AcAc/Packmol/packmol
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/H2O_AcAc/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_AcAc/ASEGeoOpt/model_outs
    - nodes/H2O_AcAc/ASEGeoOpt/trajectory.h5
    params:
    - H2O_AcAc_ASEGeoOpt
  H2O_AcAc_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name H2O_AcAc_ASEMD
    deps:
    - nodes/H2O_AcAc/ASEGeoOpt/model_outs
    - nodes/H2O_AcAc/ASEGeoOpt/node-meta.json
    - nodes/H2O_AcAc/ASEGeoOpt/trajectory.h5
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/H2O_AcAc/ASEMD/node-meta.json:
        cache: false
    - nodes/H2O_AcAc/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/H2O_AcAc/ASEMD/metrics_dict.csv
    - nodes/H2O_AcAc/ASEMD/model
    - nodes/H2O_AcAc/ASEMD/trajectory.h5
    params:
    - H2O_AcAc_ASEMD
    - H2O_AcAc_ASEMD+thermostat
  H2O_AcAc_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name H2O_AcAc_Packmol
    deps:
    - nodes/H2O_AcAc/SmilesToAtoms/atoms.h5
    - nodes/H2O_AcAc/SmilesToAtoms/molecule.png
    - nodes/H2O_AcAc/SmilesToAtoms/node-meta.json
    - nodes/H2O_AcAc/SmilesToAtoms_1/atoms.h5
    - nodes/H2O_AcAc/SmilesToAtoms_1/molecule.png
    - nodes/H2O_AcAc/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/H2O_AcAc/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_AcAc/Packmol/atoms.h5
    - nodes/H2O_AcAc/Packmol/packmol
    params:
    - H2O_AcAc_Packmol
  H2O_AcAc_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name H2O_AcAc_SmilesToAtoms
    metrics:
    - nodes/H2O_AcAc/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_AcAc/SmilesToAtoms/atoms.h5
    - nodes/H2O_AcAc/SmilesToAtoms/molecule.png
    params:
    - H2O_AcAc_SmilesToAtoms
  H2O_AcAc_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name H2O_AcAc_SmilesToAtoms_1
    metrics:
    - nodes/H2O_AcAc/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_AcAc/SmilesToAtoms_1/atoms.h5
    - nodes/H2O_AcAc/SmilesToAtoms_1/molecule.png
    params:
    - H2O_AcAc_SmilesToAtoms_1
  H2O_H2SO4_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name H2O_H2SO4_ASEGeoOpt
    deps:
    - nodes/H2O_H2SO4/Packmol/atoms.h5
    - nodes/H2O_H2SO4/Packmol/node-meta.json
    - nodes/H2O_H2SO4/Packmol/packmol
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/H2O_H2SO4/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_H2SO4/ASEGeoOpt/model_outs
    - nodes/H2O_H2SO4/ASEGeoOpt/trajectory.h5
    params:
    - H2O_H2SO4_ASEGeoOpt
  H2O_H2SO4_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name H2O_H2SO4_ASEMD
    deps:
    - nodes/H2O_H2SO4/ASEGeoOpt/model_outs
    - nodes/H2O_H2SO4/ASEGeoOpt/node-meta.json
    - nodes/H2O_H2SO4/ASEGeoOpt/trajectory.h5
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/H2O_H2SO4/ASEMD/node-meta.json:
        cache: false
    - nodes/H2O_H2SO4/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/H2O_H2SO4/ASEMD/metrics_dict.csv
    - nodes/H2O_H2SO4/ASEMD/model
    - nodes/H2O_H2SO4/ASEMD/trajectory.h5
    params:
    - H2O_H2SO4_ASEMD
    - H2O_H2SO4_ASEMD+thermostat
  H2O_H2SO4_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name H2O_H2SO4_Packmol
    deps:
    - nodes/H2O_H2SO4/SmilesToAtoms/atoms.h5
    - nodes/H2O_H2SO4/SmilesToAtoms/molecule.png
    - nodes/H2O_H2SO4/SmilesToAtoms/node-meta.json
    - nodes/H2O_H2SO4/SmilesToAtoms_1/atoms.h5
    - nodes/H2O_H2SO4/SmilesToAtoms_1/molecule.png
    - nodes/H2O_H2SO4/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/H2O_H2SO4/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_H2SO4/Packmol/atoms.h5
    - nodes/H2O_H2SO4/Packmol/packmol
    params:
    - H2O_H2SO4_Packmol
  H2O_H2SO4_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name H2O_H2SO4_SmilesToAtoms
    metrics:
    - nodes/H2O_H2SO4/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_H2SO4/SmilesToAtoms/atoms.h5
    - nodes/H2O_H2SO4/SmilesToAtoms/molecule.png
    params:
    - H2O_H2SO4_SmilesToAtoms
  H2O_H2SO4_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name H2O_H2SO4_SmilesToAtoms_1
    metrics:
    - nodes/H2O_H2SO4/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/H2O_H2SO4/SmilesToAtoms_1/atoms.h5
    - nodes/H2O_H2SO4/SmilesToAtoms_1/molecule.png
    params:
    - H2O_H2SO4_SmilesToAtoms_1
  H2O_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name H2O_Packmol
    deps:
    - nodes/H2O/SmilesToAtoms/atoms.h5
    - nodes/H2O/SmilesToAtoms/molecule.png
    - nodes/H2O/SmilesToAtoms/node-meta.json
    metrics:
    - nodes/H2O/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/H2O/Packmol/atoms.h5
    - nodes/H2O/Packmol/packmol
    params:
    - H2O_Packmol
  H2O_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name H2O_SmilesToAtoms
    metrics:
    - nodes/H2O/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/H2O/SmilesToAtoms/atoms.h5
    - nodes/H2O/SmilesToAtoms/molecule.png
    params:
    - H2O_SmilesToAtoms
  LoadModel:
    cmd: zntrack run src.LoadModel --name LoadModel
    deps:
    - 2023-08-14-mace-universal.model
    metrics:
    - nodes/LoadModel/node-meta.json:
        cache: false
