plots:
- nodes/BMIM_BF4/ASEMD/metrics_dict.csv: {}
- nodes/BMIM_BF4/BoxScale/energies.csv:
    x: x
    x_label: Scale factor of the initial cell
    y: y
    y_label: predicted energy
stages:
  BMIM_BF4_ASEGeoOpt:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_BF4_ASEGeoOpt
    deps:
    - nodes/BMIM_BF4/Packmol_1/atoms.h5
    - nodes/BMIM_BF4/Packmol_1/node-meta.json
    - nodes/BMIM_BF4/Packmol_1/packmol
    - nodes/LoadModelDispersion/node-meta.json
    metrics:
    - nodes/BMIM_BF4/ASEGeoOpt/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/ASEGeoOpt/model_outs
    - nodes/BMIM_BF4/ASEGeoOpt/trajectory.h5
    params:
    - BMIM_BF4_ASEGeoOpt
  BMIM_BF4_ASEGeoOpt_1:
    cmd: zntrack run ipsuite.nodes.ASEGeoOpt --name BMIM_BF4_ASEGeoOpt_1
    deps:
    - nodes/BMIM_BF4/Packmol_1/atoms.h5
    - nodes/BMIM_BF4/Packmol_1/node-meta.json
    - nodes/BMIM_BF4/Packmol_1/packmol
    - nodes/LoadModelDispersion/node-meta.json
    metrics:
    - nodes/BMIM_BF4/ASEGeoOpt_1/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/ASEGeoOpt_1/model_outs
    - nodes/BMIM_BF4/ASEGeoOpt_1/trajectory.h5
    params:
    - BMIM_BF4_ASEGeoOpt_1
  BMIM_BF4_ASEMD:
    cmd: zntrack run ipsuite.nodes.ASEMD --name BMIM_BF4_ASEMD
    deps:
    - nodes/BMIM_BF4/ASEGeoOpt/model_outs
    - nodes/BMIM_BF4/ASEGeoOpt/node-meta.json
    - nodes/BMIM_BF4/ASEGeoOpt/trajectory.h5
    - nodes/LoadModelDispersion/node-meta.json
    metrics:
    - nodes/BMIM_BF4/ASEMD/node-meta.json:
        cache: false
    - nodes/BMIM_BF4/ASEMD/steps_before_stopping.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/ASEMD/metrics_dict.csv
    - nodes/BMIM_BF4/ASEMD/model
    - nodes/BMIM_BF4/ASEMD/trajectory.h5
    params:
    - BMIM_BF4_ASEMD
    - BMIM_BF4_ASEMD+modifier+0
    - BMIM_BF4_ASEMD+thermostat
  BMIM_BF4_BoxScale:
    cmd: zntrack run ipsuite.nodes.BoxScale --name BMIM_BF4_BoxScale
    deps:
    - nodes/BMIM_BF4/ASEGeoOpt_1/model_outs
    - nodes/BMIM_BF4/ASEGeoOpt_1/node-meta.json
    - nodes/BMIM_BF4/ASEGeoOpt_1/trajectory.h5
    - nodes/LoadModel/node-meta.json
    metrics:
    - nodes/BMIM_BF4/BoxScale/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/BoxScale/atoms.h5
    - nodes/BMIM_BF4/BoxScale/energies.csv
    - nodes/BMIM_BF4/BoxScale/energy.png
    - nodes/BMIM_BF4/BoxScale/model
    params:
    - BMIM_BF4_BoxScale
    - BMIM_BF4_BoxScale+mapping
  BMIM_BF4_Packmol:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_BF4_Packmol
    deps:
    - nodes/BMIM_BF4/SmilesToAtoms/atoms.h5
    - nodes/BMIM_BF4/SmilesToAtoms/molecule.png
    - nodes/BMIM_BF4/SmilesToAtoms/node-meta.json
    - nodes/BMIM_BF4/SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_BF4/SmilesToAtoms_1/molecule.png
    - nodes/BMIM_BF4/SmilesToAtoms_1/node-meta.json
    metrics:
    - nodes/BMIM_BF4/Packmol/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/Packmol/atoms.h5
    - nodes/BMIM_BF4/Packmol/packmol
    params:
    - BMIM_BF4_Packmol
  BMIM_BF4_Packmol_1:
    cmd: zntrack run ipsuite.nodes.Packmol --name BMIM_BF4_Packmol_1
    deps:
    - nodes/BMIM_BF4/Packmol/atoms.h5
    - nodes/BMIM_BF4/Packmol/node-meta.json
    - nodes/BMIM_BF4/Packmol/packmol
    metrics:
    - nodes/BMIM_BF4/Packmol_1/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/Packmol_1/atoms.h5
    - nodes/BMIM_BF4/Packmol_1/packmol
    params:
    - BMIM_BF4_Packmol_1
  BMIM_BF4_SmilesToAtoms:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_BF4_SmilesToAtoms
    metrics:
    - nodes/BMIM_BF4/SmilesToAtoms/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/SmilesToAtoms/atoms.h5
    - nodes/BMIM_BF4/SmilesToAtoms/molecule.png
    params:
    - BMIM_BF4_SmilesToAtoms
  BMIM_BF4_SmilesToAtoms_1:
    cmd: zntrack run ipsuite.nodes.SmilesToAtoms --name BMIM_BF4_SmilesToAtoms_1
    metrics:
    - nodes/BMIM_BF4/SmilesToAtoms_1/node-meta.json:
        cache: false
    outs:
    - nodes/BMIM_BF4/SmilesToAtoms_1/atoms.h5
    - nodes/BMIM_BF4/SmilesToAtoms_1/molecule.png
    params:
    - BMIM_BF4_SmilesToAtoms_1
  LoadModel:
    cmd: zntrack run src.LoadModel --name LoadModel
    deps:
    - 2023-08-14-mace-universal.model
    metrics:
    - nodes/LoadModel/node-meta.json:
        cache: false
  LoadModelDispersion:
    cmd: zntrack run src.LoadModelDispersion --name LoadModelDispersion
    deps:
    - 2023-08-14-mace-universal.model
    metrics:
    - nodes/LoadModelDispersion/node-meta.json:
        cache: false
  BMIM_BF4_CP2KSinglePoint:
    cmd: zntrack run ipsuite.nodes.CP2KSinglePoint --name BMIM_BF4_CP2KSinglePoint
    deps:
    - GTH_BASIS_SETS
    - GTH_POTENTIALS
    - dftd3.dat
    - nodes/BMIM_BF4/BoxScale/atoms.h5
    - nodes/BMIM_BF4/BoxScale/energies.csv
    - nodes/BMIM_BF4/BoxScale/energy.png
    - nodes/BMIM_BF4/BoxScale/model
    - nodes/BMIM_BF4/BoxScale/node-meta.json
    params:
    - config/cp2k.yaml:
    outs:
    - nodes/BMIM_BF4/CP2KSinglePoint/atoms.h5
    - nodes/BMIM_BF4/CP2KSinglePoint/cp2k
    metrics:
    - nodes/BMIM_BF4/CP2KSinglePoint/node-meta.json:
        cache: false
