BMIM_BF4_ASEGeoOpt:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
BMIM_BF4_ASEGeoOpt_1:
    data_id: -1
    dump_rate: 1000
    init_kwargs: {}
    optimizer: FIRE
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.5
BMIM_BF4_ASEMD:
    data_id: -1
    dump_rate: 1000
    pop_last: false
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 10
    seed: 42
    steps: 1000
    use_momenta: false
    wrap: false
BMIM_BF4_ASEMD+modifier+0:
    cell: null
    density: 1196
BMIM_BF4_ASEMD+thermostat:
    friction: 0.01
    temperature: 303.15
    time_step: 0.5
BMIM_BF4_BoxScale:
    data_id: -1
    num: 50
    start: 0.9
    stop: 2.0
BMIM_BF4_BoxScale+mapping:
    frozen: false
BMIM_BF4_Packmol:
    box: null
    count:
    - 1
    - 1
    data_ids: null
    density: 1000
    pbc: false
    tolerance: 2.0
BMIM_BF4_Packmol_1:
    box: null
    count:
    - 10
    data_ids: null
    density: 700
    pbc: true
    tolerance: 2.0
BMIM_BF4_SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: CCCCN1C=C[N+](=C1)C
BMIM_BF4_SmilesToAtoms_1:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: '[B-](F)(F)(F)F'
